### ISSUE TITLE
C팀

### ISSUE THREAD

**Issue by CT-1326** [iot-nextop/IOT#13]
주제 : 날씨 관련

**Comment by sysun0813** [comment]
https://blog.naver.com/compass1111/221133450681
아두이노로 날씨정보 가져오기 관련 사이트입니다.

**Comment by sysun0813** [comment]
우노 보드는 제가 이미 가지고있어서 와이파이 쉴드로 사면 될거같아요

**Comment by tnsgud9** [comment]
## TODO
가습기 모듈 http://www.11st.co.kr/product/SellerProductDetail.tmall?method=getSellerProductDetail&prdNo=2282349971&gclid=Cj0KCQjwn_LrBRD4ARIsAFEQFKvuUY67U9EqHZBbW5cT8845EA5Z94JgtZ2q-mT0XYvA2R1H_Nxssx4aAt-aEALw_wcB&utm_term=&utm_campaign=%B1%B8%B1%DB%BC%EE%C7%CEPC+%C3%DF%B0%A1%C0%DB%BE%F7&utm_source=%B1%B8%B1%DB_PC_S_%BC%EE%C7%CE&utm_medium=%B0%CB%BB%F6

물펌프 센서 
http://shopping.interpark.com/product/productInfo.do?prdNo=6021574366&gclid=Cj0KCQjwn_LrBRD4ARIsAFEQFKvM4bm6XhBgZJvRzmtt42ojBqJUYtJ57xXkbphixNWGoB5dMw6J3RcaAvD9EALw_wcB

아두이노 WIFI ESP 
http://www.devicemart.co.kr/goods/view?no=1312096

글루건

LED

아크릴 보드 ( ? )
