### ISSUE TITLE
면접 준비 질문

### ISSUE THREAD

**Issue by Hyunjae-r** [iot-nextop/IOT#19]
IoT프로젝트에 대한 면접 질문 대비를 위해 이번 IoT프로젝트에서 쓰인 서버와 데이터베이스에 대해 설명이나 공부해야 할 목록 부탁드립니다.
@BSAA0203

**Comment by CT-1326** [comment]
필요한 날짜가 어떻게 되지?

**Comment by Hyunjae-r** [comment]
내일 12시에 면접 있습니다...

**Comment by CT-1326** [comment]
IOT 란?

아두이노 란?, IOT 개발로 아두이노를 선택한 이유는?

WIFI 란?, 아두이노로 WIFI 통신하는 방법, 그 둘의 조합으로 서버를 만들거나 호스팅 하는 방법 혹은 원리

DB와 DBMS 정의, 관계형 비관계형 차이

JSON 정의, Firebase 란?


이정도 준비해가면 충분할꺼같다 나머진 본인 소속된 팀 주제에 해당하는 공부해가길

**Comment by Hyunjae-r** [comment]
감사합니다.
