### ISSUE TITLE
스마트 팜 (A팀)

### ISSUE THREAD

**Issue by Hyunjae-r** [iot-nextop/IOT#6]
주제: 스마트 팜(식물 농장)
목표: 습도센서를 이용한 토양의 습도 측정, PH센서를 이용한 산도 측정 등을 통해 얻어낸 데이터 확인하여 물이나 비료를 통해 식물이 자라기 위한 최적의 환경을 만듦.
P.S 습도센서면 습도 센서, PH센서면 PH센서, 조도센서, 이산화 탄소 센서, 산소 센서 등등 대부분의 센서를 달 수 있는 효자 프로젝트

**Comment by yunty** [comment]
.

**Comment by KimMyoungSeop** [comment]
굿굿

**Comment by CT-1326** [comment]
위 3명은 한 팀 그룹 되었습니다. 필요한 재료 구매 등 여기 게시판에서 결정해서 얘기들 나누세요

**Comment by CT-1326** [comment]
> 위 3 명은 한 팀 그룹. 필요한 재료 구매 등

쉽게 A팀이라 부르겟습니다

**Comment by CT-1326** [comment]
> > 위 3 명은 한 팀 그룹. 필요한 재료 구매 등
> 
> 쉽게 A팀이라 부르겟습니다


게시판 작성에는 오른쪽 메뉴를 활용하면 좋습니다

Assignees : 해당 게시물 관련 담당자 지정.... 팀 구분 같은 게시물에 좋음

Labels : 게시물 관련 태그 지정.... 버그 보고, 공지, 문서 등 다양하게 활용 가능

**Comment by KimMyoungSeop** [comment]
재료 생각나는대로
센서 : 온도 습도 조도 PH
온습도센서 : http://www.devicemart.co.kr/goods/view?no=1383893
http://www.devicemart.co.kr/goods/view?no=1327420

토양습도센서 : http://www.devicemart.co.kr/goods/view?no=1376532
PH,산소,CO2센서는 가격비쌈
전체적인 모습은 https://www.devicemart.co.kr/goods/view?no=10918322 참고해도 좋을듯

**Comment by Hyunjae-r** [comment]
재료에 대한 자료조사 감사합니다.
위 자료를 기반으로 재료에 대해서는 일요일날 모여서 상의하는게 좋을것 같습니다.
이후에도 추가하고싶은 센서에 대해서는 공유 바랍니다.
저는 개인으로 아두이노 키트와 와이파이 쉴드 구입할 것입니다. 혹시 구입하기 꺼려지시는 분은 공동 프로젝트니 같이 공유해서 사용해도 좋을것 같습니다.

**Comment by yunty** [comment]
자료감사합니다.

**Comment by KimMyoungSeop** [comment]
mosfet모듈 : https://smartstore.naver.com/makerspace/products/2667897048?NaPm=ct%3Dk0akccg0%7Cci%3D9f9ba0c3337e95763c2db31744baff1daed50e5a%7Ctr%3Dsls%7Csn%3D525290%7Chk%3Dc0b1601895225e1d49b2c2acaeb811259d1cb927
펌프 : http://www.devicemart.co.kr/goods/view?no=1329770
led스트립
컴퓨터팬
식물

**Comment by Hyunjae-r** [comment]
[스마트 팜.docx](https://github.com/iot-nextop/IOT/files/3587395/default.docx)

**Comment by yunty** [comment]
[스마트팜 논문.pdf](https://github.com/iot-nextop/IOT/files/3587414/default.pdf)

**Comment by KimMyoungSeop** [comment]
[스마트팜.zip](https://github.com/iot-nextop/IOT/files/3587418/default.zip)

**Comment by Hyunjae-r** [comment]
Led strip은 가격이 좀 있네요.
Led strip 대신 3색 rgb led로 하는건 어떻게 생각하시나요?

**Comment by yunty** [comment]
괜찮은거 같아요
