### ISSUE TITLE
와이파이 쉴드 질문

### ISSUE THREAD

**Issue by Hyunjae-r** [iot-nextop/IOT#9]
<img width="775" alt="캡처" src="https://user-images.githubusercontent.com/54229231/64102413-e3b5fd00-cdaa-11e9-8099-9addbb54ef6d.PNG">
사진_1
<img width="867" alt="캡처_1" src="https://user-images.githubusercontent.com/54229231/64102487-106a1480-cdab-11e9-8242-1b9f9778faef.PNG">
사진_2

두 사진 모두 ESP8266이라는 모델명이 들어간 모델입니다.
1번 사진이 참고사진으로 올려주셨던 사진인데 가격이 10만원대입니다. 
둘 중 뭘 사도 상관 없나요?

**Comment by CT-1326** [comment]
만원 안팎인 모델이 호환 모델로써 그 모델들로 사는게 좋음 

두번째 사진껀 무선 랜 확장보드 까지 있는거라 굳이 필요한 모델은 아님
